compiler:
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3"

networks:
  default: development
  development:
    mainnet-fork:
      cmd_settings:
        fork_block: 14713470
  mainnet-fork:
    cmd_settings:
      fork_block: 14713470

reports:
  exclude_paths:
    - interfaces/**/*.*

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3
