[profile.default]
src = "contracts"
libs = ["node_modules", "lib"]

solc="0.8.11"
fs_permissions = [{access="read",path="./v2.mainnet.json"}, {access="read",path="./v3.arbitrum-one.json"}]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable",
]
verbosity = 3

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
[etherscan]
arbitrum = { key = "${ARBISCAN_KEY}", chain = 42161 }
